// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: postInfo.proto

package server

import (
	"context"

	"go-zero_less/postcenter/cmd/rpc/internal/logic/commentsinfo"
	"go-zero_less/postcenter/cmd/rpc/internal/svc"
	"go-zero_less/postcenter/cmd/rpc/pb"
)

type CommentsInfoServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCommentsInfoServer
}

func NewCommentsInfoServer(svcCtx *svc.ServiceContext) *CommentsInfoServer {
	return &CommentsInfoServer{
		svcCtx: svcCtx,
	}
}

func (s *CommentsInfoServer) GetCommentsInfoListPage(ctx context.Context, in *pb.CommentPostId) (*pb.CommentsInfoListPage, error) {
	l := commentsinfologic.NewGetCommentsInfoListPageLogic(ctx, s.svcCtx)
	return l.GetCommentsInfoListPage(in)
}

func (s *CommentsInfoServer) GetCommentsInfoDetail(ctx context.Context, in *pb.CommentsInfoId) (*pb.CommentsInfoDetail, error) {
	l := commentsinfologic.NewGetCommentsInfoDetailLogic(ctx, s.svcCtx)
	return l.GetCommentsInfoDetail(in)
}

func (s *CommentsInfoServer) CreateCommentsInfo(ctx context.Context, in *pb.CommentsInfoCreateRequest) (*pb.CommentsInfoId, error) {
	l := commentsinfologic.NewCreateCommentsInfoLogic(ctx, s.svcCtx)
	return l.CreateCommentsInfo(in)
}

func (s *CommentsInfoServer) DeleteCommentsInfo(ctx context.Context, in *pb.CommentsInfoId) (*pb.CommentsInfoDeleteResponse, error) {
	l := commentsinfologic.NewDeleteCommentsInfoLogic(ctx, s.svcCtx)
	return l.DeleteCommentsInfo(in)
}
