// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: commentsInfo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommentsInfoBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	UserId        uint64                 `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	PostId        uint64                 `protobuf:"varint,4,opt,name=postId,proto3" json:"postId,omitempty"`
	CreatedAt     uint64                 `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     uint64                 `protobuf:"varint,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	DeletedAt     uint64                 `protobuf:"varint,7,opt,name=deletedAt,proto3" json:"deletedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentsInfoBase) Reset() {
	*x = CommentsInfoBase{}
	mi := &file_commentsInfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentsInfoBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentsInfoBase) ProtoMessage() {}

func (x *CommentsInfoBase) ProtoReflect() protoreflect.Message {
	mi := &file_commentsInfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentsInfoBase.ProtoReflect.Descriptor instead.
func (*CommentsInfoBase) Descriptor() ([]byte, []int) {
	return file_commentsInfo_proto_rawDescGZIP(), []int{0}
}

func (x *CommentsInfoBase) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommentsInfoBase) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentsInfoBase) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommentsInfoBase) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CommentsInfoBase) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CommentsInfoBase) GetUpdatedAt() uint64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *CommentsInfoBase) GetDeletedAt() uint64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

type CommentsInfoList struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CommentsInfoList []*CommentsInfoBase    `protobuf:"bytes,1,rep,name=commentsInfoList,proto3" json:"commentsInfoList,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CommentsInfoList) Reset() {
	*x = CommentsInfoList{}
	mi := &file_commentsInfo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentsInfoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentsInfoList) ProtoMessage() {}

func (x *CommentsInfoList) ProtoReflect() protoreflect.Message {
	mi := &file_commentsInfo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentsInfoList.ProtoReflect.Descriptor instead.
func (*CommentsInfoList) Descriptor() ([]byte, []int) {
	return file_commentsInfo_proto_rawDescGZIP(), []int{1}
}

func (x *CommentsInfoList) GetCommentsInfoList() []*CommentsInfoBase {
	if x != nil {
		return x.CommentsInfoList
	}
	return nil
}

type CommentsInfoId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentsInfoId) Reset() {
	*x = CommentsInfoId{}
	mi := &file_commentsInfo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentsInfoId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentsInfoId) ProtoMessage() {}

func (x *CommentsInfoId) ProtoReflect() protoreflect.Message {
	mi := &file_commentsInfo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentsInfoId.ProtoReflect.Descriptor instead.
func (*CommentsInfoId) Descriptor() ([]byte, []int) {
	return file_commentsInfo_proto_rawDescGZIP(), []int{2}
}

func (x *CommentsInfoId) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CommentPostId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentPostId) Reset() {
	*x = CommentPostId{}
	mi := &file_commentsInfo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentPostId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentPostId) ProtoMessage() {}

func (x *CommentPostId) ProtoReflect() protoreflect.Message {
	mi := &file_commentsInfo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentPostId.ProtoReflect.Descriptor instead.
func (*CommentPostId) Descriptor() ([]byte, []int) {
	return file_commentsInfo_proto_rawDescGZIP(), []int{3}
}

func (x *CommentPostId) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type UserInfoId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoId) Reset() {
	*x = UserInfoId{}
	mi := &file_commentsInfo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoId) ProtoMessage() {}

func (x *UserInfoId) ProtoReflect() protoreflect.Message {
	mi := &file_commentsInfo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoId.ProtoReflect.Descriptor instead.
func (*UserInfoId) Descriptor() ([]byte, []int) {
	return file_commentsInfo_proto_rawDescGZIP(), []int{4}
}

func (x *UserInfoId) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CommentsInfoListPage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CommentsInfoList []*CommentsInfoBase    `protobuf:"bytes,1,rep,name=commentsInfoList,proto3" json:"commentsInfoList,omitempty"`
	Total            uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page             uint64                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize         uint64                 `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CommentsInfoListPage) Reset() {
	*x = CommentsInfoListPage{}
	mi := &file_commentsInfo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentsInfoListPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentsInfoListPage) ProtoMessage() {}

func (x *CommentsInfoListPage) ProtoReflect() protoreflect.Message {
	mi := &file_commentsInfo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentsInfoListPage.ProtoReflect.Descriptor instead.
func (*CommentsInfoListPage) Descriptor() ([]byte, []int) {
	return file_commentsInfo_proto_rawDescGZIP(), []int{5}
}

func (x *CommentsInfoListPage) GetCommentsInfoList() []*CommentsInfoBase {
	if x != nil {
		return x.CommentsInfoList
	}
	return nil
}

func (x *CommentsInfoListPage) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CommentsInfoListPage) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CommentsInfoListPage) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type CommentsInfoDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentsInfo  *CommentsInfoBase      `protobuf:"bytes,1,opt,name=commentsInfo,proto3" json:"commentsInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentsInfoDetail) Reset() {
	*x = CommentsInfoDetail{}
	mi := &file_commentsInfo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentsInfoDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentsInfoDetail) ProtoMessage() {}

func (x *CommentsInfoDetail) ProtoReflect() protoreflect.Message {
	mi := &file_commentsInfo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentsInfoDetail.ProtoReflect.Descriptor instead.
func (*CommentsInfoDetail) Descriptor() ([]byte, []int) {
	return file_commentsInfo_proto_rawDescGZIP(), []int{6}
}

func (x *CommentsInfoDetail) GetCommentsInfo() *CommentsInfoBase {
	if x != nil {
		return x.CommentsInfo
	}
	return nil
}

type CommentsInfoCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentsInfo  *CommentsInfoBase      `protobuf:"bytes,1,opt,name=commentsInfo,proto3" json:"commentsInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentsInfoCreateRequest) Reset() {
	*x = CommentsInfoCreateRequest{}
	mi := &file_commentsInfo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentsInfoCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentsInfoCreateRequest) ProtoMessage() {}

func (x *CommentsInfoCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commentsInfo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentsInfoCreateRequest.ProtoReflect.Descriptor instead.
func (*CommentsInfoCreateRequest) Descriptor() ([]byte, []int) {
	return file_commentsInfo_proto_rawDescGZIP(), []int{7}
}

func (x *CommentsInfoCreateRequest) GetCommentsInfo() *CommentsInfoBase {
	if x != nil {
		return x.CommentsInfo
	}
	return nil
}

type CommentsInfoDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentsInfoDeleteRequest) Reset() {
	*x = CommentsInfoDeleteRequest{}
	mi := &file_commentsInfo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentsInfoDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentsInfoDeleteRequest) ProtoMessage() {}

func (x *CommentsInfoDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commentsInfo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentsInfoDeleteRequest.ProtoReflect.Descriptor instead.
func (*CommentsInfoDeleteRequest) Descriptor() ([]byte, []int) {
	return file_commentsInfo_proto_rawDescGZIP(), []int{8}
}

func (x *CommentsInfoDeleteRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CommentsInfoDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentsInfoDeleteResponse) Reset() {
	*x = CommentsInfoDeleteResponse{}
	mi := &file_commentsInfo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentsInfoDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentsInfoDeleteResponse) ProtoMessage() {}

func (x *CommentsInfoDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commentsInfo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentsInfoDeleteResponse.ProtoReflect.Descriptor instead.
func (*CommentsInfoDeleteResponse) Descriptor() ([]byte, []int) {
	return file_commentsInfo_proto_rawDescGZIP(), []int{9}
}

func (x *CommentsInfoDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_commentsInfo_proto protoreflect.FileDescriptor

const file_commentsInfo_proto_rawDesc = "" +
	"\n" +
	"\x12commentsInfo.proto\x12\x02pb\"\xc6\x01\n" +
	"\x10CommentsInfoBase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06postId\x18\x04 \x01(\x04R\x06postId\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\x04R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x06 \x01(\x04R\tupdatedAt\x12\x1c\n" +
	"\tdeletedAt\x18\a \x01(\x04R\tdeletedAt\"T\n" +
	"\x10CommentsInfoList\x12@\n" +
	"\x10commentsInfoList\x18\x01 \x03(\v2\x14.pb.CommentsInfoBaseR\x10commentsInfoList\" \n" +
	"\x0eCommentsInfoId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"'\n" +
	"\rCommentPostId\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\x04R\x06postId\"$\n" +
	"\n" +
	"UserInfoId\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\"\x9e\x01\n" +
	"\x14CommentsInfoListPage\x12@\n" +
	"\x10commentsInfoList\x18\x01 \x03(\v2\x14.pb.CommentsInfoBaseR\x10commentsInfoList\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x04R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x04R\bpageSize\"N\n" +
	"\x12CommentsInfoDetail\x128\n" +
	"\fcommentsInfo\x18\x01 \x01(\v2\x14.pb.CommentsInfoBaseR\fcommentsInfo\"U\n" +
	"\x19CommentsInfoCreateRequest\x128\n" +
	"\fcommentsInfo\x18\x01 \x01(\v2\x14.pb.CommentsInfoBaseR\fcommentsInfo\"+\n" +
	"\x19CommentsInfoDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"6\n" +
	"\x1aCommentsInfoDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB\x06Z\x04./pbb\x06proto3"

var (
	file_commentsInfo_proto_rawDescOnce sync.Once
	file_commentsInfo_proto_rawDescData []byte
)

func file_commentsInfo_proto_rawDescGZIP() []byte {
	file_commentsInfo_proto_rawDescOnce.Do(func() {
		file_commentsInfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_commentsInfo_proto_rawDesc), len(file_commentsInfo_proto_rawDesc)))
	})
	return file_commentsInfo_proto_rawDescData
}

var file_commentsInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_commentsInfo_proto_goTypes = []any{
	(*CommentsInfoBase)(nil),           // 0: pb.CommentsInfoBase
	(*CommentsInfoList)(nil),           // 1: pb.CommentsInfoList
	(*CommentsInfoId)(nil),             // 2: pb.CommentsInfoId
	(*CommentPostId)(nil),              // 3: pb.CommentPostId
	(*UserInfoId)(nil),                 // 4: pb.UserInfoId
	(*CommentsInfoListPage)(nil),       // 5: pb.CommentsInfoListPage
	(*CommentsInfoDetail)(nil),         // 6: pb.CommentsInfoDetail
	(*CommentsInfoCreateRequest)(nil),  // 7: pb.CommentsInfoCreateRequest
	(*CommentsInfoDeleteRequest)(nil),  // 8: pb.CommentsInfoDeleteRequest
	(*CommentsInfoDeleteResponse)(nil), // 9: pb.CommentsInfoDeleteResponse
}
var file_commentsInfo_proto_depIdxs = []int32{
	0, // 0: pb.CommentsInfoList.commentsInfoList:type_name -> pb.CommentsInfoBase
	0, // 1: pb.CommentsInfoListPage.commentsInfoList:type_name -> pb.CommentsInfoBase
	0, // 2: pb.CommentsInfoDetail.commentsInfo:type_name -> pb.CommentsInfoBase
	0, // 3: pb.CommentsInfoCreateRequest.commentsInfo:type_name -> pb.CommentsInfoBase
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_commentsInfo_proto_init() }
func file_commentsInfo_proto_init() {
	if File_commentsInfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commentsInfo_proto_rawDesc), len(file_commentsInfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commentsInfo_proto_goTypes,
		DependencyIndexes: file_commentsInfo_proto_depIdxs,
		MessageInfos:      file_commentsInfo_proto_msgTypes,
	}.Build()
	File_commentsInfo_proto = out.File
	file_commentsInfo_proto_goTypes = nil
	file_commentsInfo_proto_depIdxs = nil
}
