// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: postInfo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 评论信息
type CommentsInfoBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	UserId        uint64                 `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	PostId        uint64                 `protobuf:"varint,4,opt,name=postId,proto3" json:"postId,omitempty"`
	CreatedAt     uint64                 `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     uint64                 `protobuf:"varint,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	DeletedAt     uint64                 `protobuf:"varint,7,opt,name=deletedAt,proto3" json:"deletedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentsInfoBase) Reset() {
	*x = CommentsInfoBase{}
	mi := &file_postInfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentsInfoBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentsInfoBase) ProtoMessage() {}

func (x *CommentsInfoBase) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentsInfoBase.ProtoReflect.Descriptor instead.
func (*CommentsInfoBase) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{0}
}

func (x *CommentsInfoBase) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommentsInfoBase) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentsInfoBase) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommentsInfoBase) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CommentsInfoBase) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CommentsInfoBase) GetUpdatedAt() uint64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *CommentsInfoBase) GetDeletedAt() uint64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

type CommentsInfoList struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CommentsInfoList []*CommentsInfoBase    `protobuf:"bytes,1,rep,name=commentsInfoList,proto3" json:"commentsInfoList,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CommentsInfoList) Reset() {
	*x = CommentsInfoList{}
	mi := &file_postInfo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentsInfoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentsInfoList) ProtoMessage() {}

func (x *CommentsInfoList) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentsInfoList.ProtoReflect.Descriptor instead.
func (*CommentsInfoList) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{1}
}

func (x *CommentsInfoList) GetCommentsInfoList() []*CommentsInfoBase {
	if x != nil {
		return x.CommentsInfoList
	}
	return nil
}

type CommentsInfoId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentsInfoId) Reset() {
	*x = CommentsInfoId{}
	mi := &file_postInfo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentsInfoId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentsInfoId) ProtoMessage() {}

func (x *CommentsInfoId) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentsInfoId.ProtoReflect.Descriptor instead.
func (*CommentsInfoId) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{2}
}

func (x *CommentsInfoId) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CommentPostId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentPostId) Reset() {
	*x = CommentPostId{}
	mi := &file_postInfo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentPostId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentPostId) ProtoMessage() {}

func (x *CommentPostId) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentPostId.ProtoReflect.Descriptor instead.
func (*CommentPostId) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{3}
}

func (x *CommentPostId) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type UserInfoId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoId) Reset() {
	*x = UserInfoId{}
	mi := &file_postInfo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoId) ProtoMessage() {}

func (x *UserInfoId) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoId.ProtoReflect.Descriptor instead.
func (*UserInfoId) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{4}
}

func (x *UserInfoId) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CommentsInfoListPage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CommentsInfoList []*CommentsInfoBase    `protobuf:"bytes,1,rep,name=commentsInfoList,proto3" json:"commentsInfoList,omitempty"`
	Total            uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page             uint64                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize         uint64                 `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CommentsInfoListPage) Reset() {
	*x = CommentsInfoListPage{}
	mi := &file_postInfo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentsInfoListPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentsInfoListPage) ProtoMessage() {}

func (x *CommentsInfoListPage) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentsInfoListPage.ProtoReflect.Descriptor instead.
func (*CommentsInfoListPage) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{5}
}

func (x *CommentsInfoListPage) GetCommentsInfoList() []*CommentsInfoBase {
	if x != nil {
		return x.CommentsInfoList
	}
	return nil
}

func (x *CommentsInfoListPage) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CommentsInfoListPage) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CommentsInfoListPage) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type CommentsInfoDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentsInfo  *CommentsInfoBase      `protobuf:"bytes,1,opt,name=commentsInfo,proto3" json:"commentsInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentsInfoDetail) Reset() {
	*x = CommentsInfoDetail{}
	mi := &file_postInfo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentsInfoDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentsInfoDetail) ProtoMessage() {}

func (x *CommentsInfoDetail) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentsInfoDetail.ProtoReflect.Descriptor instead.
func (*CommentsInfoDetail) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{6}
}

func (x *CommentsInfoDetail) GetCommentsInfo() *CommentsInfoBase {
	if x != nil {
		return x.CommentsInfo
	}
	return nil
}

type CommentsInfoCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentsInfo  *CommentsInfoBase      `protobuf:"bytes,1,opt,name=commentsInfo,proto3" json:"commentsInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentsInfoCreateRequest) Reset() {
	*x = CommentsInfoCreateRequest{}
	mi := &file_postInfo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentsInfoCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentsInfoCreateRequest) ProtoMessage() {}

func (x *CommentsInfoCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentsInfoCreateRequest.ProtoReflect.Descriptor instead.
func (*CommentsInfoCreateRequest) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{7}
}

func (x *CommentsInfoCreateRequest) GetCommentsInfo() *CommentsInfoBase {
	if x != nil {
		return x.CommentsInfo
	}
	return nil
}

type CommentsInfoDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentsInfoDeleteRequest) Reset() {
	*x = CommentsInfoDeleteRequest{}
	mi := &file_postInfo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentsInfoDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentsInfoDeleteRequest) ProtoMessage() {}

func (x *CommentsInfoDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentsInfoDeleteRequest.ProtoReflect.Descriptor instead.
func (*CommentsInfoDeleteRequest) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{8}
}

func (x *CommentsInfoDeleteRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CommentsInfoDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentsInfoDeleteResponse) Reset() {
	*x = CommentsInfoDeleteResponse{}
	mi := &file_postInfo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentsInfoDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentsInfoDeleteResponse) ProtoMessage() {}

func (x *CommentsInfoDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentsInfoDeleteResponse.ProtoReflect.Descriptor instead.
func (*CommentsInfoDeleteResponse) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{9}
}

func (x *CommentsInfoDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 帖子信息
type PostInfoBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	UserId        uint64                 `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	CreatedAt     uint64                 `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     uint64                 `protobuf:"varint,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	DeletedAt     uint64                 `protobuf:"varint,7,opt,name=deletedAt,proto3" json:"deletedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfoBase) Reset() {
	*x = PostInfoBase{}
	mi := &file_postInfo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfoBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfoBase) ProtoMessage() {}

func (x *PostInfoBase) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfoBase.ProtoReflect.Descriptor instead.
func (*PostInfoBase) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{10}
}

func (x *PostInfoBase) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostInfoBase) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostInfoBase) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PostInfoBase) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostInfoBase) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PostInfoBase) GetUpdatedAt() uint64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *PostInfoBase) GetDeletedAt() uint64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

type PostInfoList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostInfoList  []*PostInfoBase        `protobuf:"bytes,1,rep,name=postInfoList,proto3" json:"postInfoList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfoList) Reset() {
	*x = PostInfoList{}
	mi := &file_postInfo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfoList) ProtoMessage() {}

func (x *PostInfoList) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfoList.ProtoReflect.Descriptor instead.
func (*PostInfoList) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{11}
}

func (x *PostInfoList) GetPostInfoList() []*PostInfoBase {
	if x != nil {
		return x.PostInfoList
	}
	return nil
}

type PostInfoListPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostInfoList  []*PostInfoBase        `protobuf:"bytes,1,rep,name=postInfoList,proto3" json:"postInfoList,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          uint64                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint64                 `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfoListPage) Reset() {
	*x = PostInfoListPage{}
	mi := &file_postInfo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfoListPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfoListPage) ProtoMessage() {}

func (x *PostInfoListPage) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfoListPage.ProtoReflect.Descriptor instead.
func (*PostInfoListPage) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{12}
}

func (x *PostInfoListPage) GetPostInfoList() []*PostInfoBase {
	if x != nil {
		return x.PostInfoList
	}
	return nil
}

func (x *PostInfoListPage) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PostInfoListPage) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PostInfoListPage) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PostInfoId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfoId) Reset() {
	*x = PostInfoId{}
	mi := &file_postInfo_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfoId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfoId) ProtoMessage() {}

func (x *PostInfoId) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfoId.ProtoReflect.Descriptor instead.
func (*PostInfoId) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{13}
}

func (x *PostInfoId) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PostInfoDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostInfo      *PostInfoBase          `protobuf:"bytes,1,opt,name=postInfo,proto3" json:"postInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfoDetail) Reset() {
	*x = PostInfoDetail{}
	mi := &file_postInfo_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfoDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfoDetail) ProtoMessage() {}

func (x *PostInfoDetail) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfoDetail.ProtoReflect.Descriptor instead.
func (*PostInfoDetail) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{14}
}

func (x *PostInfoDetail) GetPostInfo() *PostInfoBase {
	if x != nil {
		return x.PostInfo
	}
	return nil
}

type PostInfoDetailWithComments struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	PostInfo         *PostInfoBase           `protobuf:"bytes,1,opt,name=postInfo,proto3" json:"postInfo,omitempty"`
	CommentsInfoList []*CommentsInfoListPage `protobuf:"bytes,2,rep,name=commentsInfoList,proto3" json:"commentsInfoList,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PostInfoDetailWithComments) Reset() {
	*x = PostInfoDetailWithComments{}
	mi := &file_postInfo_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfoDetailWithComments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfoDetailWithComments) ProtoMessage() {}

func (x *PostInfoDetailWithComments) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfoDetailWithComments.ProtoReflect.Descriptor instead.
func (*PostInfoDetailWithComments) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{15}
}

func (x *PostInfoDetailWithComments) GetPostInfo() *PostInfoBase {
	if x != nil {
		return x.PostInfo
	}
	return nil
}

func (x *PostInfoDetailWithComments) GetCommentsInfoList() []*CommentsInfoListPage {
	if x != nil {
		return x.CommentsInfoList
	}
	return nil
}

type PostInfoCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostInfo      *PostInfoBase          `protobuf:"bytes,1,opt,name=postInfo,proto3" json:"postInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfoCreateRequest) Reset() {
	*x = PostInfoCreateRequest{}
	mi := &file_postInfo_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfoCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfoCreateRequest) ProtoMessage() {}

func (x *PostInfoCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfoCreateRequest.ProtoReflect.Descriptor instead.
func (*PostInfoCreateRequest) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{16}
}

func (x *PostInfoCreateRequest) GetPostInfo() *PostInfoBase {
	if x != nil {
		return x.PostInfo
	}
	return nil
}

type PostInfoUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostInfo      *PostInfoBase          `protobuf:"bytes,1,opt,name=postInfo,proto3" json:"postInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfoUpdateRequest) Reset() {
	*x = PostInfoUpdateRequest{}
	mi := &file_postInfo_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfoUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfoUpdateRequest) ProtoMessage() {}

func (x *PostInfoUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfoUpdateRequest.ProtoReflect.Descriptor instead.
func (*PostInfoUpdateRequest) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{17}
}

func (x *PostInfoUpdateRequest) GetPostInfo() *PostInfoBase {
	if x != nil {
		return x.PostInfo
	}
	return nil
}

type PostInfoDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfoDeleteResponse) Reset() {
	*x = PostInfoDeleteResponse{}
	mi := &file_postInfo_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfoDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfoDeleteResponse) ProtoMessage() {}

func (x *PostInfoDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfoDeleteResponse.ProtoReflect.Descriptor instead.
func (*PostInfoDeleteResponse) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{18}
}

func (x *PostInfoDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ExecRows struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          uint64                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRows) Reset() {
	*x = ExecRows{}
	mi := &file_postInfo_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRows) ProtoMessage() {}

func (x *ExecRows) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRows.ProtoReflect.Descriptor instead.
func (*ExecRows) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{19}
}

func (x *ExecRows) GetRows() uint64 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type PostInfoCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfoCountRequest) Reset() {
	*x = PostInfoCountRequest{}
	mi := &file_postInfo_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfoCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfoCountRequest) ProtoMessage() {}

func (x *PostInfoCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfoCountRequest.ProtoReflect.Descriptor instead.
func (*PostInfoCountRequest) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{20}
}

func (x *PostInfoCountRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type PostInfoCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint64                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfoCountResponse) Reset() {
	*x = PostInfoCountResponse{}
	mi := &file_postInfo_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfoCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfoCountResponse) ProtoMessage() {}

func (x *PostInfoCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfoCountResponse.ProtoReflect.Descriptor instead.
func (*PostInfoCountResponse) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{21}
}

func (x *PostInfoCountResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 请求msg
type PostSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Page          uint64                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint64                 `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	StartDate     uint64                 `protobuf:"varint,5,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate       uint64                 `protobuf:"varint,6,opt,name=endDate,proto3" json:"endDate,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostSearchRequest) Reset() {
	*x = PostSearchRequest{}
	mi := &file_postInfo_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostSearchRequest) ProtoMessage() {}

func (x *PostSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostSearchRequest.ProtoReflect.Descriptor instead.
func (*PostSearchRequest) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{22}
}

func (x *PostSearchRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *PostSearchRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostSearchRequest) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PostSearchRequest) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PostSearchRequest) GetStartDate() uint64 {
	if x != nil {
		return x.StartDate
	}
	return 0
}

func (x *PostSearchRequest) GetEndDate() uint64 {
	if x != nil {
		return x.EndDate
	}
	return 0
}

func (x *PostSearchRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_postInfo_proto protoreflect.FileDescriptor

const file_postInfo_proto_rawDesc = "" +
	"\n" +
	"\x0epostInfo.proto\x12\x02pb\"\xc6\x01\n" +
	"\x10CommentsInfoBase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06postId\x18\x04 \x01(\x04R\x06postId\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\x04R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x06 \x01(\x04R\tupdatedAt\x12\x1c\n" +
	"\tdeletedAt\x18\a \x01(\x04R\tdeletedAt\"T\n" +
	"\x10CommentsInfoList\x12@\n" +
	"\x10commentsInfoList\x18\x01 \x03(\v2\x14.pb.CommentsInfoBaseR\x10commentsInfoList\" \n" +
	"\x0eCommentsInfoId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"'\n" +
	"\rCommentPostId\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\x04R\x06postId\"$\n" +
	"\n" +
	"UserInfoId\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\"\x9e\x01\n" +
	"\x14CommentsInfoListPage\x12@\n" +
	"\x10commentsInfoList\x18\x01 \x03(\v2\x14.pb.CommentsInfoBaseR\x10commentsInfoList\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x04R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x04R\bpageSize\"N\n" +
	"\x12CommentsInfoDetail\x128\n" +
	"\fcommentsInfo\x18\x01 \x01(\v2\x14.pb.CommentsInfoBaseR\fcommentsInfo\"U\n" +
	"\x19CommentsInfoCreateRequest\x128\n" +
	"\fcommentsInfo\x18\x01 \x01(\v2\x14.pb.CommentsInfoBaseR\fcommentsInfo\"+\n" +
	"\x19CommentsInfoDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"6\n" +
	"\x1aCommentsInfoDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xc0\x01\n" +
	"\fPostInfoBase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x16\n" +
	"\x06userId\x18\x04 \x01(\x04R\x06userId\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\x04R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x06 \x01(\x04R\tupdatedAt\x12\x1c\n" +
	"\tdeletedAt\x18\a \x01(\x04R\tdeletedAt\"D\n" +
	"\fPostInfoList\x124\n" +
	"\fpostInfoList\x18\x01 \x03(\v2\x10.pb.PostInfoBaseR\fpostInfoList\"\x8e\x01\n" +
	"\x10PostInfoListPage\x124\n" +
	"\fpostInfoList\x18\x01 \x03(\v2\x10.pb.PostInfoBaseR\fpostInfoList\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x04R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x04R\bpageSize\"\x1c\n" +
	"\n" +
	"PostInfoId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\">\n" +
	"\x0ePostInfoDetail\x12,\n" +
	"\bpostInfo\x18\x01 \x01(\v2\x10.pb.PostInfoBaseR\bpostInfo\"\x90\x01\n" +
	"\x1aPostInfoDetailWithComments\x12,\n" +
	"\bpostInfo\x18\x01 \x01(\v2\x10.pb.PostInfoBaseR\bpostInfo\x12D\n" +
	"\x10commentsInfoList\x18\x02 \x03(\v2\x18.pb.CommentsInfoListPageR\x10commentsInfoList\"E\n" +
	"\x15PostInfoCreateRequest\x12,\n" +
	"\bpostInfo\x18\x01 \x01(\v2\x10.pb.PostInfoBaseR\bpostInfo\"E\n" +
	"\x15PostInfoUpdateRequest\x12,\n" +
	"\bpostInfo\x18\x01 \x01(\v2\x10.pb.PostInfoBaseR\bpostInfo\"2\n" +
	"\x16PostInfoDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x1e\n" +
	"\bexecRows\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\x04R\x04rows\".\n" +
	"\x14PostInfoCountRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\"-\n" +
	"\x15PostInfoCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x04R\x05count\"\xc5\x01\n" +
	"\x11PostSearchRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x04R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x04R\bpageSize\x12\x1c\n" +
	"\tstartDate\x18\x05 \x01(\x04R\tstartDate\x12\x18\n" +
	"\aendDate\x18\x06 \x01(\x04R\aendDate\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status2\xcc\x04\n" +
	"\bPostInfo\x12>\n" +
	"\x0fGetPostListPage\x12\x15.pb.PostSearchRequest\x1a\x14.pb.PostInfoListPage\x12?\n" +
	"\rGetPostDetail\x12\x0e.pb.PostInfoId\x1a\x1e.pb.PostInfoDetailWithComments\x127\n" +
	"\n" +
	"CreatePost\x12\x19.pb.PostInfoCreateRequest\x1a\x0e.pb.PostInfoId\x128\n" +
	"\n" +
	"DeletePost\x12\x0e.pb.PostInfoId\x1a\x1a.pb.PostInfoDeleteResponse\x12,\n" +
	"\n" +
	"UpdatePost\x12\x10.pb.PostInfoBase\x1a\f.pb.execRows\x12F\n" +
	"\x17GetCommentsInfoListPage\x12\x11.pb.CommentPostId\x1a\x18.pb.CommentsInfoListPage\x12C\n" +
	"\x15GetCommentsInfoDetail\x12\x12.pb.CommentsInfoId\x1a\x16.pb.CommentsInfoDetail\x12G\n" +
	"\x12CreateCommentsInfo\x12\x1d.pb.CommentsInfoCreateRequest\x1a\x12.pb.CommentsInfoId\x12H\n" +
	"\x12DeleteCommentsInfo\x12\x12.pb.CommentsInfoId\x1a\x1e.pb.CommentsInfoDeleteResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_postInfo_proto_rawDescOnce sync.Once
	file_postInfo_proto_rawDescData []byte
)

func file_postInfo_proto_rawDescGZIP() []byte {
	file_postInfo_proto_rawDescOnce.Do(func() {
		file_postInfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_postInfo_proto_rawDesc), len(file_postInfo_proto_rawDesc)))
	})
	return file_postInfo_proto_rawDescData
}

var file_postInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_postInfo_proto_goTypes = []any{
	(*CommentsInfoBase)(nil),           // 0: pb.CommentsInfoBase
	(*CommentsInfoList)(nil),           // 1: pb.CommentsInfoList
	(*CommentsInfoId)(nil),             // 2: pb.CommentsInfoId
	(*CommentPostId)(nil),              // 3: pb.CommentPostId
	(*UserInfoId)(nil),                 // 4: pb.UserInfoId
	(*CommentsInfoListPage)(nil),       // 5: pb.CommentsInfoListPage
	(*CommentsInfoDetail)(nil),         // 6: pb.CommentsInfoDetail
	(*CommentsInfoCreateRequest)(nil),  // 7: pb.CommentsInfoCreateRequest
	(*CommentsInfoDeleteRequest)(nil),  // 8: pb.CommentsInfoDeleteRequest
	(*CommentsInfoDeleteResponse)(nil), // 9: pb.CommentsInfoDeleteResponse
	(*PostInfoBase)(nil),               // 10: pb.PostInfoBase
	(*PostInfoList)(nil),               // 11: pb.PostInfoList
	(*PostInfoListPage)(nil),           // 12: pb.PostInfoListPage
	(*PostInfoId)(nil),                 // 13: pb.PostInfoId
	(*PostInfoDetail)(nil),             // 14: pb.PostInfoDetail
	(*PostInfoDetailWithComments)(nil), // 15: pb.PostInfoDetailWithComments
	(*PostInfoCreateRequest)(nil),      // 16: pb.PostInfoCreateRequest
	(*PostInfoUpdateRequest)(nil),      // 17: pb.PostInfoUpdateRequest
	(*PostInfoDeleteResponse)(nil),     // 18: pb.PostInfoDeleteResponse
	(*ExecRows)(nil),                   // 19: pb.execRows
	(*PostInfoCountRequest)(nil),       // 20: pb.PostInfoCountRequest
	(*PostInfoCountResponse)(nil),      // 21: pb.PostInfoCountResponse
	(*PostSearchRequest)(nil),          // 22: pb.PostSearchRequest
}
var file_postInfo_proto_depIdxs = []int32{
	0,  // 0: pb.CommentsInfoList.commentsInfoList:type_name -> pb.CommentsInfoBase
	0,  // 1: pb.CommentsInfoListPage.commentsInfoList:type_name -> pb.CommentsInfoBase
	0,  // 2: pb.CommentsInfoDetail.commentsInfo:type_name -> pb.CommentsInfoBase
	0,  // 3: pb.CommentsInfoCreateRequest.commentsInfo:type_name -> pb.CommentsInfoBase
	10, // 4: pb.PostInfoList.postInfoList:type_name -> pb.PostInfoBase
	10, // 5: pb.PostInfoListPage.postInfoList:type_name -> pb.PostInfoBase
	10, // 6: pb.PostInfoDetail.postInfo:type_name -> pb.PostInfoBase
	10, // 7: pb.PostInfoDetailWithComments.postInfo:type_name -> pb.PostInfoBase
	5,  // 8: pb.PostInfoDetailWithComments.commentsInfoList:type_name -> pb.CommentsInfoListPage
	10, // 9: pb.PostInfoCreateRequest.postInfo:type_name -> pb.PostInfoBase
	10, // 10: pb.PostInfoUpdateRequest.postInfo:type_name -> pb.PostInfoBase
	22, // 11: pb.PostInfo.GetPostListPage:input_type -> pb.PostSearchRequest
	13, // 12: pb.PostInfo.GetPostDetail:input_type -> pb.PostInfoId
	16, // 13: pb.PostInfo.CreatePost:input_type -> pb.PostInfoCreateRequest
	13, // 14: pb.PostInfo.DeletePost:input_type -> pb.PostInfoId
	10, // 15: pb.PostInfo.UpdatePost:input_type -> pb.PostInfoBase
	3,  // 16: pb.PostInfo.GetCommentsInfoListPage:input_type -> pb.CommentPostId
	2,  // 17: pb.PostInfo.GetCommentsInfoDetail:input_type -> pb.CommentsInfoId
	7,  // 18: pb.PostInfo.CreateCommentsInfo:input_type -> pb.CommentsInfoCreateRequest
	2,  // 19: pb.PostInfo.DeleteCommentsInfo:input_type -> pb.CommentsInfoId
	12, // 20: pb.PostInfo.GetPostListPage:output_type -> pb.PostInfoListPage
	15, // 21: pb.PostInfo.GetPostDetail:output_type -> pb.PostInfoDetailWithComments
	13, // 22: pb.PostInfo.CreatePost:output_type -> pb.PostInfoId
	18, // 23: pb.PostInfo.DeletePost:output_type -> pb.PostInfoDeleteResponse
	19, // 24: pb.PostInfo.UpdatePost:output_type -> pb.execRows
	5,  // 25: pb.PostInfo.GetCommentsInfoListPage:output_type -> pb.CommentsInfoListPage
	6,  // 26: pb.PostInfo.GetCommentsInfoDetail:output_type -> pb.CommentsInfoDetail
	2,  // 27: pb.PostInfo.CreateCommentsInfo:output_type -> pb.CommentsInfoId
	9,  // 28: pb.PostInfo.DeleteCommentsInfo:output_type -> pb.CommentsInfoDeleteResponse
	20, // [20:29] is the sub-list for method output_type
	11, // [11:20] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_postInfo_proto_init() }
func file_postInfo_proto_init() {
	if File_postInfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_postInfo_proto_rawDesc), len(file_postInfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_postInfo_proto_goTypes,
		DependencyIndexes: file_postInfo_proto_depIdxs,
		MessageInfos:      file_postInfo_proto_msgTypes,
	}.Build()
	File_postInfo_proto = out.File
	file_postInfo_proto_goTypes = nil
	file_postInfo_proto_depIdxs = nil
}
