// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: postInfo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostInfoBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	UserId        uint64                 `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	CreatedAt     uint64                 `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     uint64                 `protobuf:"varint,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	DeletedAt     uint64                 `protobuf:"varint,7,opt,name=deletedAt,proto3" json:"deletedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfoBase) Reset() {
	*x = PostInfoBase{}
	mi := &file_postInfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfoBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfoBase) ProtoMessage() {}

func (x *PostInfoBase) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfoBase.ProtoReflect.Descriptor instead.
func (*PostInfoBase) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{0}
}

func (x *PostInfoBase) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostInfoBase) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostInfoBase) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PostInfoBase) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostInfoBase) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PostInfoBase) GetUpdatedAt() uint64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *PostInfoBase) GetDeletedAt() uint64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

type PostInfoList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostInfoList  []*PostInfoBase        `protobuf:"bytes,1,rep,name=postInfoList,proto3" json:"postInfoList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfoList) Reset() {
	*x = PostInfoList{}
	mi := &file_postInfo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfoList) ProtoMessage() {}

func (x *PostInfoList) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfoList.ProtoReflect.Descriptor instead.
func (*PostInfoList) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{1}
}

func (x *PostInfoList) GetPostInfoList() []*PostInfoBase {
	if x != nil {
		return x.PostInfoList
	}
	return nil
}

type PostInfoListPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostInfoList  []*PostInfoBase        `protobuf:"bytes,1,rep,name=postInfoList,proto3" json:"postInfoList,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          uint64                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint64                 `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfoListPage) Reset() {
	*x = PostInfoListPage{}
	mi := &file_postInfo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfoListPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfoListPage) ProtoMessage() {}

func (x *PostInfoListPage) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfoListPage.ProtoReflect.Descriptor instead.
func (*PostInfoListPage) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{2}
}

func (x *PostInfoListPage) GetPostInfoList() []*PostInfoBase {
	if x != nil {
		return x.PostInfoList
	}
	return nil
}

func (x *PostInfoListPage) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PostInfoListPage) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PostInfoListPage) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PostInfoId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfoId) Reset() {
	*x = PostInfoId{}
	mi := &file_postInfo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfoId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfoId) ProtoMessage() {}

func (x *PostInfoId) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfoId.ProtoReflect.Descriptor instead.
func (*PostInfoId) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{3}
}

func (x *PostInfoId) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PostInfoDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostInfo      *PostInfoBase          `protobuf:"bytes,1,opt,name=postInfo,proto3" json:"postInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfoDetail) Reset() {
	*x = PostInfoDetail{}
	mi := &file_postInfo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfoDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfoDetail) ProtoMessage() {}

func (x *PostInfoDetail) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfoDetail.ProtoReflect.Descriptor instead.
func (*PostInfoDetail) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{4}
}

func (x *PostInfoDetail) GetPostInfo() *PostInfoBase {
	if x != nil {
		return x.PostInfo
	}
	return nil
}

type PostInfoDetailWithComments struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	PostInfo         *PostInfoBase           `protobuf:"bytes,1,opt,name=postInfo,proto3" json:"postInfo,omitempty"`
	CommentsInfoList []*CommentsInfoListPage `protobuf:"bytes,2,rep,name=commentsInfoList,proto3" json:"commentsInfoList,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PostInfoDetailWithComments) Reset() {
	*x = PostInfoDetailWithComments{}
	mi := &file_postInfo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfoDetailWithComments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfoDetailWithComments) ProtoMessage() {}

func (x *PostInfoDetailWithComments) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfoDetailWithComments.ProtoReflect.Descriptor instead.
func (*PostInfoDetailWithComments) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{5}
}

func (x *PostInfoDetailWithComments) GetPostInfo() *PostInfoBase {
	if x != nil {
		return x.PostInfo
	}
	return nil
}

func (x *PostInfoDetailWithComments) GetCommentsInfoList() []*CommentsInfoListPage {
	if x != nil {
		return x.CommentsInfoList
	}
	return nil
}

type PostInfoCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostInfo      *PostInfoBase          `protobuf:"bytes,1,opt,name=postInfo,proto3" json:"postInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfoCreateRequest) Reset() {
	*x = PostInfoCreateRequest{}
	mi := &file_postInfo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfoCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfoCreateRequest) ProtoMessage() {}

func (x *PostInfoCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfoCreateRequest.ProtoReflect.Descriptor instead.
func (*PostInfoCreateRequest) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{6}
}

func (x *PostInfoCreateRequest) GetPostInfo() *PostInfoBase {
	if x != nil {
		return x.PostInfo
	}
	return nil
}

type PostInfoUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostInfo      *PostInfoBase          `protobuf:"bytes,1,opt,name=postInfo,proto3" json:"postInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfoUpdateRequest) Reset() {
	*x = PostInfoUpdateRequest{}
	mi := &file_postInfo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfoUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfoUpdateRequest) ProtoMessage() {}

func (x *PostInfoUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfoUpdateRequest.ProtoReflect.Descriptor instead.
func (*PostInfoUpdateRequest) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{7}
}

func (x *PostInfoUpdateRequest) GetPostInfo() *PostInfoBase {
	if x != nil {
		return x.PostInfo
	}
	return nil
}

type PostInfoDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfoDeleteResponse) Reset() {
	*x = PostInfoDeleteResponse{}
	mi := &file_postInfo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfoDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfoDeleteResponse) ProtoMessage() {}

func (x *PostInfoDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfoDeleteResponse.ProtoReflect.Descriptor instead.
func (*PostInfoDeleteResponse) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{8}
}

func (x *PostInfoDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ExecRows struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          uint64                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRows) Reset() {
	*x = ExecRows{}
	mi := &file_postInfo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRows) ProtoMessage() {}

func (x *ExecRows) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRows.ProtoReflect.Descriptor instead.
func (*ExecRows) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{9}
}

func (x *ExecRows) GetRows() uint64 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type PostInfoCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfoCountRequest) Reset() {
	*x = PostInfoCountRequest{}
	mi := &file_postInfo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfoCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfoCountRequest) ProtoMessage() {}

func (x *PostInfoCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfoCountRequest.ProtoReflect.Descriptor instead.
func (*PostInfoCountRequest) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{10}
}

func (x *PostInfoCountRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type PostInfoCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint64                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfoCountResponse) Reset() {
	*x = PostInfoCountResponse{}
	mi := &file_postInfo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfoCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfoCountResponse) ProtoMessage() {}

func (x *PostInfoCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfoCountResponse.ProtoReflect.Descriptor instead.
func (*PostInfoCountResponse) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{11}
}

func (x *PostInfoCountResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 请求msg
type PostSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Page          uint64                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint64                 `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	StartDate     uint64                 `protobuf:"varint,5,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate       uint64                 `protobuf:"varint,6,opt,name=endDate,proto3" json:"endDate,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostSearchRequest) Reset() {
	*x = PostSearchRequest{}
	mi := &file_postInfo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostSearchRequest) ProtoMessage() {}

func (x *PostSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postInfo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostSearchRequest.ProtoReflect.Descriptor instead.
func (*PostSearchRequest) Descriptor() ([]byte, []int) {
	return file_postInfo_proto_rawDescGZIP(), []int{12}
}

func (x *PostSearchRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *PostSearchRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostSearchRequest) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PostSearchRequest) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PostSearchRequest) GetStartDate() uint64 {
	if x != nil {
		return x.StartDate
	}
	return 0
}

func (x *PostSearchRequest) GetEndDate() uint64 {
	if x != nil {
		return x.EndDate
	}
	return 0
}

func (x *PostSearchRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_postInfo_proto protoreflect.FileDescriptor

const file_postInfo_proto_rawDesc = "" +
	"\n" +
	"\x0epostInfo.proto\x12\x02pb\x1a\x12commentsInfo.proto\"\xc0\x01\n" +
	"\fPostInfoBase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x16\n" +
	"\x06userId\x18\x04 \x01(\x04R\x06userId\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\x04R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x06 \x01(\x04R\tupdatedAt\x12\x1c\n" +
	"\tdeletedAt\x18\a \x01(\x04R\tdeletedAt\"D\n" +
	"\fPostInfoList\x124\n" +
	"\fpostInfoList\x18\x01 \x03(\v2\x10.pb.PostInfoBaseR\fpostInfoList\"\x8e\x01\n" +
	"\x10PostInfoListPage\x124\n" +
	"\fpostInfoList\x18\x01 \x03(\v2\x10.pb.PostInfoBaseR\fpostInfoList\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x04R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x04R\bpageSize\"\x1c\n" +
	"\n" +
	"PostInfoId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\">\n" +
	"\x0ePostInfoDetail\x12,\n" +
	"\bpostInfo\x18\x01 \x01(\v2\x10.pb.PostInfoBaseR\bpostInfo\"\x90\x01\n" +
	"\x1aPostInfoDetailWithComments\x12,\n" +
	"\bpostInfo\x18\x01 \x01(\v2\x10.pb.PostInfoBaseR\bpostInfo\x12D\n" +
	"\x10commentsInfoList\x18\x02 \x03(\v2\x18.pb.CommentsInfoListPageR\x10commentsInfoList\"E\n" +
	"\x15PostInfoCreateRequest\x12,\n" +
	"\bpostInfo\x18\x01 \x01(\v2\x10.pb.PostInfoBaseR\bpostInfo\"E\n" +
	"\x15PostInfoUpdateRequest\x12,\n" +
	"\bpostInfo\x18\x01 \x01(\v2\x10.pb.PostInfoBaseR\bpostInfo\"2\n" +
	"\x16PostInfoDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x1e\n" +
	"\bexecRows\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\x04R\x04rows\".\n" +
	"\x14PostInfoCountRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\"-\n" +
	"\x15PostInfoCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x04R\x05count\"\xc5\x01\n" +
	"\x11PostSearchRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x04R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x04R\bpageSize\x12\x1c\n" +
	"\tstartDate\x18\x05 \x01(\x04R\tstartDate\x12\x18\n" +
	"\aendDate\x18\x06 \x01(\x04R\aendDate\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status2\xac\x02\n" +
	"\bPostInfo\x12>\n" +
	"\x0fGetPostListPage\x12\x15.pb.PostSearchRequest\x1a\x14.pb.PostInfoListPage\x12?\n" +
	"\rGetPostDetail\x12\x0e.pb.PostInfoId\x1a\x1e.pb.PostInfoDetailWithComments\x127\n" +
	"\n" +
	"CreatePost\x12\x19.pb.PostInfoCreateRequest\x1a\x0e.pb.PostInfoId\x128\n" +
	"\n" +
	"DeletePost\x12\x0e.pb.PostInfoId\x1a\x1a.pb.PostInfoDeleteResponse\x12,\n" +
	"\n" +
	"UpdatePost\x12\x10.pb.PostInfoBase\x1a\f.pb.execRows2\xae\x02\n" +
	"\fCommentsInfo\x12F\n" +
	"\x17GetCommentsInfoListPage\x12\x11.pb.CommentPostId\x1a\x18.pb.CommentsInfoListPage\x12C\n" +
	"\x15GetCommentsInfoDetail\x12\x12.pb.CommentsInfoId\x1a\x16.pb.CommentsInfoDetail\x12G\n" +
	"\x12CreateCommentsInfo\x12\x1d.pb.CommentsInfoCreateRequest\x1a\x12.pb.CommentsInfoId\x12H\n" +
	"\x12DeleteCommentsInfo\x12\x12.pb.CommentsInfoId\x1a\x1e.pb.CommentsInfoDeleteResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_postInfo_proto_rawDescOnce sync.Once
	file_postInfo_proto_rawDescData []byte
)

func file_postInfo_proto_rawDescGZIP() []byte {
	file_postInfo_proto_rawDescOnce.Do(func() {
		file_postInfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_postInfo_proto_rawDesc), len(file_postInfo_proto_rawDesc)))
	})
	return file_postInfo_proto_rawDescData
}

var file_postInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_postInfo_proto_goTypes = []any{
	(*PostInfoBase)(nil),               // 0: pb.PostInfoBase
	(*PostInfoList)(nil),               // 1: pb.PostInfoList
	(*PostInfoListPage)(nil),           // 2: pb.PostInfoListPage
	(*PostInfoId)(nil),                 // 3: pb.PostInfoId
	(*PostInfoDetail)(nil),             // 4: pb.PostInfoDetail
	(*PostInfoDetailWithComments)(nil), // 5: pb.PostInfoDetailWithComments
	(*PostInfoCreateRequest)(nil),      // 6: pb.PostInfoCreateRequest
	(*PostInfoUpdateRequest)(nil),      // 7: pb.PostInfoUpdateRequest
	(*PostInfoDeleteResponse)(nil),     // 8: pb.PostInfoDeleteResponse
	(*ExecRows)(nil),                   // 9: pb.execRows
	(*PostInfoCountRequest)(nil),       // 10: pb.PostInfoCountRequest
	(*PostInfoCountResponse)(nil),      // 11: pb.PostInfoCountResponse
	(*PostSearchRequest)(nil),          // 12: pb.PostSearchRequest
	(*CommentsInfoListPage)(nil),       // 13: pb.CommentsInfoListPage
	(*CommentPostId)(nil),              // 14: pb.CommentPostId
	(*CommentsInfoId)(nil),             // 15: pb.CommentsInfoId
	(*CommentsInfoCreateRequest)(nil),  // 16: pb.CommentsInfoCreateRequest
	(*CommentsInfoDetail)(nil),         // 17: pb.CommentsInfoDetail
	(*CommentsInfoDeleteResponse)(nil), // 18: pb.CommentsInfoDeleteResponse
}
var file_postInfo_proto_depIdxs = []int32{
	0,  // 0: pb.PostInfoList.postInfoList:type_name -> pb.PostInfoBase
	0,  // 1: pb.PostInfoListPage.postInfoList:type_name -> pb.PostInfoBase
	0,  // 2: pb.PostInfoDetail.postInfo:type_name -> pb.PostInfoBase
	0,  // 3: pb.PostInfoDetailWithComments.postInfo:type_name -> pb.PostInfoBase
	13, // 4: pb.PostInfoDetailWithComments.commentsInfoList:type_name -> pb.CommentsInfoListPage
	0,  // 5: pb.PostInfoCreateRequest.postInfo:type_name -> pb.PostInfoBase
	0,  // 6: pb.PostInfoUpdateRequest.postInfo:type_name -> pb.PostInfoBase
	12, // 7: pb.PostInfo.GetPostListPage:input_type -> pb.PostSearchRequest
	3,  // 8: pb.PostInfo.GetPostDetail:input_type -> pb.PostInfoId
	6,  // 9: pb.PostInfo.CreatePost:input_type -> pb.PostInfoCreateRequest
	3,  // 10: pb.PostInfo.DeletePost:input_type -> pb.PostInfoId
	0,  // 11: pb.PostInfo.UpdatePost:input_type -> pb.PostInfoBase
	14, // 12: pb.CommentsInfo.GetCommentsInfoListPage:input_type -> pb.CommentPostId
	15, // 13: pb.CommentsInfo.GetCommentsInfoDetail:input_type -> pb.CommentsInfoId
	16, // 14: pb.CommentsInfo.CreateCommentsInfo:input_type -> pb.CommentsInfoCreateRequest
	15, // 15: pb.CommentsInfo.DeleteCommentsInfo:input_type -> pb.CommentsInfoId
	2,  // 16: pb.PostInfo.GetPostListPage:output_type -> pb.PostInfoListPage
	5,  // 17: pb.PostInfo.GetPostDetail:output_type -> pb.PostInfoDetailWithComments
	3,  // 18: pb.PostInfo.CreatePost:output_type -> pb.PostInfoId
	8,  // 19: pb.PostInfo.DeletePost:output_type -> pb.PostInfoDeleteResponse
	9,  // 20: pb.PostInfo.UpdatePost:output_type -> pb.execRows
	13, // 21: pb.CommentsInfo.GetCommentsInfoListPage:output_type -> pb.CommentsInfoListPage
	17, // 22: pb.CommentsInfo.GetCommentsInfoDetail:output_type -> pb.CommentsInfoDetail
	15, // 23: pb.CommentsInfo.CreateCommentsInfo:output_type -> pb.CommentsInfoId
	18, // 24: pb.CommentsInfo.DeleteCommentsInfo:output_type -> pb.CommentsInfoDeleteResponse
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_postInfo_proto_init() }
func file_postInfo_proto_init() {
	if File_postInfo_proto != nil {
		return
	}
	file_commentsInfo_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_postInfo_proto_rawDesc), len(file_postInfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_postInfo_proto_goTypes,
		DependencyIndexes: file_postInfo_proto_depIdxs,
		MessageInfos:      file_postInfo_proto_msgTypes,
	}.Build()
	File_postInfo_proto = out.File
	file_postInfo_proto_goTypes = nil
	file_postInfo_proto_depIdxs = nil
}
