// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: usercenter.proto

package server

import (
	"context"

	"go-zero_less/usercenter/cmd/rpc/internal/logic"
	"go-zero_less/usercenter/cmd/rpc/internal/svc"
	"go-zero_less/usercenter/cmd/rpc/pb"
)

type UsercenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUsercenterServer
}

func NewUsercenterServer(svcCtx *svc.ServiceContext) *UsercenterServer {
	return &UsercenterServer{
		svcCtx: svcCtx,
	}
}

func (s *UsercenterServer) Login(ctx context.Context, in *pb.LoginReq) (*pb.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UsercenterServer) Register(ctx context.Context, in *pb.RegisterReq) (*pb.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UsercenterServer) GetUsers(ctx context.Context, in *pb.UserInfosReq) (*pb.UserInfosResp, error) {
	l := logic.NewGetUsersLogic(ctx, s.svcCtx)
	return l.GetUsers(in)
}

func (s *UsercenterServer) GetUser(ctx context.Context, in *pb.UserInfoOneReq) (*pb.UserInfoResp, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *UsercenterServer) UserPostNumIncr(ctx context.Context, in *pb.UserPostNumReq) (*pb.ResultBool, error) {
	l := logic.NewUserPostNumIncrLogic(ctx, s.svcCtx)
	return l.UserPostNumIncr(in)
}
