// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type LoginReq struct {
	Username string `json:"uname"`
	Password string `json:"pwd"`
}

type LoginResp struct {
	Id       uint64 `json:"id"`
	Name     string `json:"name"`
	Token    string `json:"token"`
	ExpireAt string `json:"expireAt"`
}

type RegiesterReq struct {
	Username string `json:"uname"`
	Password string `json:"pwd"`
	Email    string `json:"email"`
}

type RegisterResp struct {
	Id uint64 `json:"id"`
}
