// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: postInfo.proto

package commentsinfo

import (
	"context"

	"go-zero_less/postcenter/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ExecRows                   = pb.ExecRows
	PostInfoBase               = pb.PostInfoBase
	PostInfoCountRequest       = pb.PostInfoCountRequest
	PostInfoCountResponse      = pb.PostInfoCountResponse
	PostInfoCreateRequest      = pb.PostInfoCreateRequest
	PostInfoDeleteResponse     = pb.PostInfoDeleteResponse
	PostInfoDetail             = pb.PostInfoDetail
	PostInfoDetailWithComments = pb.PostInfoDetailWithComments
	PostInfoId                 = pb.PostInfoId
	PostInfoList               = pb.PostInfoList
	PostInfoListPage           = pb.PostInfoListPage
	PostInfoUpdateRequest      = pb.PostInfoUpdateRequest
	PostSearchRequest          = pb.PostSearchRequest

	// 添加缺失的评论相关类型别名
	CommentPostId              = pb.CommentPostId
	CommentsInfoBase           = pb.CommentsInfoBase
	CommentsInfoId             = pb.CommentsInfoId
	CommentsInfoCreateRequest  = pb.CommentsInfoCreateRequest
	CommentsInfoDeleteResponse = pb.CommentsInfoDeleteResponse
	CommentsInfoListPage       = pb.CommentsInfoListPage
	CommentsInfoDetail         = pb.CommentsInfoDetail
	CommentsInfoList           = pb.CommentsInfoList
	UserInfoId                 = pb.UserInfoId

	CommentsInfo interface {
		GetCommentsInfoListPage(ctx context.Context, in *CommentPostId, opts ...grpc.CallOption) (*CommentsInfoListPage, error)
		GetCommentsInfoDetail(ctx context.Context, in *CommentsInfoId, opts ...grpc.CallOption) (*CommentsInfoDetail, error)
		CreateCommentsInfo(ctx context.Context, in *CommentsInfoCreateRequest, opts ...grpc.CallOption) (*CommentsInfoId, error)
		DeleteCommentsInfo(ctx context.Context, in *CommentsInfoId, opts ...grpc.CallOption) (*CommentsInfoDeleteResponse, error)
	}

	defaultCommentsInfo struct {
		cli zrpc.Client
	}
)

func NewCommentsInfo(cli zrpc.Client) CommentsInfo {
	return &defaultCommentsInfo{
		cli: cli,
	}
}

func (m *defaultCommentsInfo) GetCommentsInfoListPage(ctx context.Context, in *CommentPostId, opts ...grpc.CallOption) (*CommentsInfoListPage, error) {
	client := pb.NewCommentsInfoClient(m.cli.Conn())
	return client.GetCommentsInfoListPage(ctx, in, opts...)
}

func (m *defaultCommentsInfo) GetCommentsInfoDetail(ctx context.Context, in *CommentsInfoId, opts ...grpc.CallOption) (*CommentsInfoDetail, error) {
	client := pb.NewCommentsInfoClient(m.cli.Conn())
	return client.GetCommentsInfoDetail(ctx, in, opts...)
}

func (m *defaultCommentsInfo) CreateCommentsInfo(ctx context.Context, in *CommentsInfoCreateRequest, opts ...grpc.CallOption) (*CommentsInfoId, error) {
	client := pb.NewCommentsInfoClient(m.cli.Conn())
	return client.CreateCommentsInfo(ctx, in, opts...)
}

func (m *defaultCommentsInfo) DeleteCommentsInfo(ctx context.Context, in *CommentsInfoId, opts ...grpc.CallOption) (*CommentsInfoDeleteResponse, error) {
	client := pb.NewCommentsInfoClient(m.cli.Conn())
	return client.DeleteCommentsInfo(ctx, in, opts...)
}
