// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	comments "go-zero_less/postcenter/cmd/api/internal/handler/comments"
	post "go-zero_less/postcenter/cmd/api/internal/handler/post"
	"go-zero_less/postcenter/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/post/comments/:id",
				Handler: comments.GetCommentsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/post/comment",
				Handler: comments.CreateCommentHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/post",
				Handler: post.CreatePostHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/post",
				Handler: post.UpdatePostHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/post/:id",
				Handler: post.DeletePostHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/post/:id",
				Handler: post.GetPostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/posts",
				Handler: post.GetPostsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
