// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: postInfo.proto

package server

import (
	"context"

	"go-zero_less/postcenter/cmd/rpc/internal/logic/postinfo"
	"go-zero_less/postcenter/cmd/rpc/internal/svc"
	"go-zero_less/postcenter/cmd/rpc/pb"
)

type PostInfoServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedPostInfoServer
}

func NewPostInfoServer(svcCtx *svc.ServiceContext) *PostInfoServer {
	return &PostInfoServer{
		svcCtx: svcCtx,
	}
}

func (s *PostInfoServer) GetPostListPage(ctx context.Context, in *pb.PostSearchRequest) (*pb.PostInfoListPage, error) {
	l := postinfologic.NewGetPostListPageLogic(ctx, s.svcCtx)
	return l.GetPostListPage(in)
}

func (s *PostInfoServer) GetPostDetail(ctx context.Context, in *pb.PostInfoId) (*pb.PostInfoDetailWithComments, error) {
	l := postinfologic.NewGetPostDetailLogic(ctx, s.svcCtx)
	return l.GetPostDetail(in)
}

func (s *PostInfoServer) CreatePost(ctx context.Context, in *pb.PostInfoCreateRequest) (*pb.PostInfoId, error) {
	l := postinfologic.NewCreatePostLogic(ctx, s.svcCtx)
	return l.CreatePost(in)
}

func (s *PostInfoServer) DeletePost(ctx context.Context, in *pb.PostInfoId) (*pb.PostInfoDeleteResponse, error) {
	l := postinfologic.NewDeletePostLogic(ctx, s.svcCtx)
	return l.DeletePost(in)
}

func (s *PostInfoServer) UpdatePost(ctx context.Context, in *pb.PostInfoBase) (*pb.ExecRows, error) {
	l := postinfologic.NewUpdatePostLogic(ctx, s.svcCtx)
	return l.UpdatePost(in)
}
