// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type CommentsList struct {
	Id        uint64 `json:"id"`
	PostId    uint64 `json:"postId"`
	UserId    uint64 `json:"userId"`
	Content   string `json:"content"`
	CreatedAt string `json:"createdAt"`
}

type CreateCommentReq struct {
	PostId  uint64 `json:"postId"`
	UserId  uint64 `json:"userId"`
	Content string `json:"content"`
}

type CreateCommentResp struct {
	Id uint64 `json:"id"`
}

type CreatePostReq struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type CreatePostResp struct {
	Id uint64 `json:"id"`
}

type DeletePostReq struct {
	Id uint64 `json:"id"`
}

type DeletePostResp struct {
	Res bool `json:"res"`
}

type GetCommentsResp struct {
	Comments []CommentsList `json:"comments"`
}

type GetPostReq struct {
	Id uint64 `json:"id"`
}

type GetPostResp struct {
	Post PostDetail `json:"post"`
}

type GetPostsReq struct {
	KeyWord  string `json:"keyWord"`
	UserId   uint64 `json:"userId"`
	Page     int    `json:"page"`
	PageSize int    `json:"pageSize"`
}

type GetPostsResp struct {
	Posts []PostList `json:"posts"`
	Total int        `json:"total"`
}

type PostDetail struct {
	Id        uint64         `json:"id"`
	Title     string         `json:"title"`
	Content   string         `json:"content"`
	UserId    uint64         `json:"userId"`
	CreatedAt string         `json:"createdAt"`
	Comments  []CommentsList `json:"comments"`
}

type PostList struct {
	Id        uint64 `json:"id"`
	Title     string `json:"title"`
	UserId    uint64 `json:"userId"`
	CreatedAt string `json:"createdAt"`
}

type UpdatePostReq struct {
	Id      uint64 `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type UpdatePostResp struct {
	Res bool `json:"res"`
}
